---
title: "About Us"
---

The Space Coast Chess Foundation, Inc., a 501(c)(3) educational organization, is one of the premier chess organizations in Florida. Our mission is to promote the educational, scientific, cultural and sporting value of the game chess among people of all ages, with a focus on the East Central Coast of Florida (the “Space Coast”). The Foundation supports scholastic and community chess programs, provides free chess equipment, and organizes and sponsors chess events with the goal of fostering the development of chess and realizing its benefits in life-long learning.

We are best known for organizing and sponsoring the Space Coast Open Chess Festival, which has been held almost every year since 1991. We also started the local Scholastics Chess program, which is now ably run by the Space Coast Scholastic Chess Club and the Brevard Chess Center, with continued support from our Foundation.

The Space Coast Chess Foundation has received the Silver Seal of Transparency from GuideStar, a leading provider of information about non-profits. This rating places the Space Coast Chess Foundation in the top 2% of all non-profits based on transparency. Click on the logo below for more information.